/**
 * wallets/setup.ts — Phase 1.1: broker + 3 provider agent wallets.
 *
 * Design note on custody: Circle's Developer-Controlled Wallets are
 * Circle-custodied — the SDK deliberately does not hand you a raw exportable
 * private key. Every other signing surface in this repo (Deploy.s.sol,
 * contracts/scripts/register-agents.ts, contracts/scripts/post-reputation.ts,
 * and the stream loop below) is built around raw-PK signing via viem/forge.
 * Mixing custody models would mean register-agents.ts silently can't sign for
 * these wallets. So we generate plain local EOAs here instead — same trust
 * model as every other wallet in the project, and Circle CLI's
 * `wallet fund` / `gateway deposit` commands work against any address
 * regardless of who holds the key.
 *
 * Idempotent: if backend/.env.local already has wallets, this refuses to
 * regenerate them (pass --force to override) — overwriting a funded testnet
 * wallet's key is unrecoverable and would silently strand its balance.
 *
 * Usage:
 *   npm run wallets:setup
 *   npm run wallets:setup -- --force
 */

import { existsSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { loadAddresses } from "../lib/config.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENV_LOCAL_PATH = join(__dirname, "..", ".env.local");
const ADDRESSES_PATH = join(__dirname, "../../shared/addresses.json");

const ROLES = [
  { key: "broker", envPrefix: "BROKER", name: "Athena Broker" },
  { key: "provider1", envPrefix: "PROVIDER1", name: "Athena Crypto Provider" },
  { key: "provider2", envPrefix: "PROVIDER2", name: "Athena Market Analytics Provider" },
  { key: "provider3", envPrefix: "PROVIDER3", name: "Athena Price Feed Provider" },
] as const;

function parseEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    out[trimmed.slice(0, eq)] = trimmed.slice(eq + 1);
  }
  return out;
}

function main() {
  const force = process.argv.includes("--force");
  const existing = parseEnvFile(ENV_LOCAL_PATH);

  const alreadySet = ROLES.every((r) => existing[`${r.envPrefix}_PK`]);
  if (alreadySet && !force) {
    console.log("Wallets already exist in backend/.env.local — skipping generation.");
    console.log("(pass --force to regenerate; this abandons any funds on the old wallets)\n");
    printSummary(
      ROLES.map((r) => ({
        ...r,
        address: existing[`${r.envPrefix}_WALLET_ADDRESS`]!,
      }))
    );
    return;
  }

  console.log("=== Athena Backend B — Wallet Setup (Phase 1.1) ===\n");

  const generated = ROLES.map((r) => {
    const pk = generatePrivateKey();
    const account = privateKeyToAccount(pk);
    return { ...r, pk, address: account.address };
  });

  const lines = [
    "# Generated by `npm run wallets:setup` — DO NOT COMMIT",
    ...generated.flatMap((g) => [`${g.envPrefix}_PK=${g.pk}`, `${g.envPrefix}_WALLET_ADDRESS=${g.address}`]),
    "",
  ];
  writeFileSync(ENV_LOCAL_PATH, lines.join("\n"));
  console.log(`Wrote ${ROLES.length} wallets to backend/.env.local\n`);

  // Stage addresses (not keys) into shared/addresses.json so Backend A can read
  // them for H2 without private keys ever leaving this file. register-agents.ts
  // overwrites the "agents" key with tokenIds once it runs — this is a separate,
  // pre-registration staging area.
  const addressesFile = JSON.parse(readFileSync(ADDRESSES_PATH, "utf8"));
  addressesFile.backendWallets = Object.fromEntries(
    generated.map((g) => [g.key, { address: g.address, name: g.name, role: g.key === "broker" ? "broker" : "provider" }])
  );
  writeFileSync(ADDRESSES_PATH, JSON.stringify(addressesFile, null, 2) + "\n");
  console.log("Staged addresses into shared/addresses.json under \"backendWallets\"\n");

  printSummary(generated);
}

function printSummary(wallets: { key: string; name: string; address: string }[]) {
  const addresses = loadAddresses();

  console.log("── Wallet addresses ─────────────────────────────────────────");
  for (const w of wallets) console.log(`  ${w.key.padEnd(10)} ${w.address}  (${w.name})`);

  console.log("\n── Next steps (run for EACH address above) ────────────────────");
  console.log("  1. Fund with testnet USDC (native gas + ERC-20 balance):");
  console.log("       Faucet: https://faucet.circle.com (select Arc Testnet)");
  console.log("       or:     circle wallet fund --address $ADDR --chain ARC-TESTNET\n");
  console.log("  2. Broker wallet ONLY — deposit into Gateway (funds the stream's");
  console.log("     nanopayments; providers do not need a Gateway deposit):");
  console.log(
    `       circle gateway deposit --amount 10 --address ${wallets[0]?.address} --chain ARC-TESTNET --method direct\n`
  );
  console.log("  3. Broker wallet ONLY — approve AthenaCommit to pull the bond:");
  console.log(
    `       cast send ${addresses.contracts.usdc} "approve(address,uint256)" ${addresses.contracts.athenaCommit} <bondAmount> --rpc-url arc_testnet --private-key $BROKER_PK\n`
  );

  console.log("── H2 handoff → send this to Backend A ─────────────────────────");
  for (const w of wallets.filter((w) => w.key !== "broker")) {
    console.log(`  ${w.key}: ${w.address}  (role: provider)`);
  }
  console.log("\n  Backend A needs these to run: cd contracts/scripts && npm run register");
  console.log("  (that script also needs BROKER_PK/PROVIDER{1,2,3}_PK as DEPLOYER_PK/PROVIDERn_PK —");
  console.log("   copy them from backend/.env.local into that command's environment, it is not read automatically)");
}

main();
