import { config as loadEnv } from "dotenv";
import { readFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import type { Abi } from "viem";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "../..");
const SHARED_DIR = join(REPO_ROOT, "shared");

// .env holds committed defaults (ports etc.), .env.local holds real secrets
// generated by `npm run wallets:setup` — .env.local is gitignored.
loadEnv({ path: join(__dirname, "..", ".env") });
loadEnv({ path: join(__dirname, "..", ".env.local"), override: true });

export interface AthenaAddresses {
  chainId: number;
  network: string;
  rpc: string;
  rpc_public: string;
  explorer: string;
  contracts: {
    athenaCommit: string;
    usdc: string;
    eurc: string;
    erc8183: string;
    erc8004Identity: string;
    erc8004Reputation: string;
    gatewayWallet: string;
    gatewayMinter: string;
    cctpTokenMessengerV2: string;
    cctpMessageTransmitterV2: string;
    cctpTokenMinterV2: string;
    multicall3: string;
    permit2: string;
    create2Factory: string;
  };
  agents: Record<string, { address: string; tokenId: string; name: string; role: string }>;
}

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf8")) as T;
}

// Read fresh on every call (not cached at module load) — Backend A updates this
// file after deploys/registrations and we should never serve a stale snapshot.
export function loadAddresses(): AthenaAddresses {
  return readJson<AthenaAddresses>(join(SHARED_DIR, "addresses.json"));
}

export function loadAthenaCommitAbi() {
  return readJson<unknown[]>(join(SHARED_DIR, "abis", "AthenaCommit.json"));
}

export const addresses = loadAddresses();
export const athenaCommitAbi = loadAthenaCommitAbi() as Abi;

export const USDC_DECIMALS = 6;

export function usdcToUnits(amount: number): bigint {
  return BigInt(Math.round(amount * 10 ** USDC_DECIMALS));
}

export function unitsToUsdc(units: bigint): number {
  return Number(units) / 10 ** USDC_DECIMALS;
}
